apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: search-engine-crawler
build:
  artifacts:
    - image: your-repo/search-engine # This must match the image in deployment.yaml
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}
