apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: querymesh
data:
  KAFKA_BROKER: kafka:9092
  KAFKA_TOPIC: urls
  KAFKA_GROUP_ID: crawler-consumer
  WORKER_COUNT: "4"
  HTTP_TIMEOUT: 10s
  SHUTDOWN_TIMEOUT: 15s
  EXECUTION_MODE: consumer
